language: c

os:
  - linux 64 bit

before_install:
  - sudo apt-get update -y
  - sudo apt-get install bison build-essential curl flex git git-core gnupg flex bison zip
  - sudo apt-get install -y ccache &&echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc &&source ~/.bashrc && echo $PATH
  - export USE_CCACHE=1

before_script:
# Download the toolchain
  - git clone https://github.com/techdro-id/aarch64-linux-android -b SDK26 $HOME/kernel/toolchain/SDK26
# Download the Kernel Sources
  - git clone https://github.com/techdro-id/stormguard_mido_msm8953 -b CAF/AOSP-LOS $HOME/kernel/mido

  - git clone https://github.com/techdro-id/AnyKernel2 -b mido $HOME/kernel/anykernel/mido

  - git clone https://github.com/techdro-id/zip.git $HOME/kernel/files/mido

script:
  - export ARCH=arm64
  - export KERNELDIR=$HOME/kernel/mido
  - cd $KERNELDIR
  - ./build

notifications:
  email:
    recipents:
      - adek@techdro.id
    on_failure: never
